package ssl;
/* Generated By:JJTree&JavaCC: Do not edit this line. ExpressionParserConstants.java */

/**
 * Token literal values and constants.
 * Generated by org.javacc.parser.OtherFilesGen#start()
 */
public interface ExpressionParserConstants {

  /** End of File. */
  int EOF = 0;
  /** RegularExpression Id. */
  int ADD = 4;
  /** RegularExpression Id. */
  int DO = 5;
  /** RegularExpression Id. */
  int UPDATE = 6;
  /** RegularExpression Id. */
  int LINK = 7;
  /** RegularExpression Id. */
  int QUANTIFIER = 8;
  /** RegularExpression Id. */
  int SUCH_THAT = 9;
  /** RegularExpression Id. */
  int WHERE = 10;
  /** RegularExpression Id. */
  int AND = 11;
  /** RegularExpression Id. */
  int ALL = 12;
  /** RegularExpression Id. */
  int EOC = 13;
  /** RegularExpression Id. */
  int ASSIGN = 14;
  /** RegularExpression Id. */
  int NUMBER = 15;
  /** RegularExpression Id. */
  int STRING = 16;
  /** RegularExpression Id. */
  int SPACES = 17;
  /** RegularExpression Id. */
  int DIGIT = 18;
  /** RegularExpression Id. */
  int LETTER = 19;
  /** RegularExpression Id. */
  int SPACE = 20;

  /** Lexical state. */
  int DEFAULT = 0;

  /** Literal token values. */
  String[] tokenImage = {
    "<EOF>",
    "\"\\t\"",
    "\"\\n\"",
    "\"\\r\"",
    "<ADD>",
    "<DO>",
    "<UPDATE>",
    "<LINK>",
    "<QUANTIFIER>",
    "\"SUCH THAT\"",
    "<WHERE>",
    "<AND>",
    "\"*\"",
    "<EOC>",
    "<ASSIGN>",
    "<NUMBER>",
    "<STRING>",
    "<SPACES>",
    "<DIGIT>",
    "<LETTER>",
    "\" \"",
  };

}
