package ssl;
/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 5.0 */
public interface ExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTADDSTATEMENT = 2;
  public int JJTDOSTATEMENT = 3;
  public int JJTUPDATESTATEMENT = 4;
  public int JJTQUANTIFIER = 5;
  public int JJTNUMBER = 6;
  public int JJTALL = 7;
  public int JJTCLASS = 8;
  public int JJTASSIGNMENTS = 9;
  public int JJTASSIGNMENT = 10;
  public int JJTPROPERTY = 11;
  public int JJTVALUE = 12;


  public String[] jjtNodeName = {
    "Start",
    "void",
    "AddStatement",
    "DoStatement",
    "UpdateStatement",
    "Quantifier",
    "Number",
    "All",
    "Class",
    "Assignments",
    "Assignment",
    "Property",
    "Value",
  };
}
/* JavaCC - OriginalChecksum=b6929064441a4df9005e91c4ab99b81d (do not edit this line) */
