package ssl;
/* Generated By:JavaCC: Do not edit this line. ExpressionParserVisitor.java Version 5.0 */
public interface ExpressionParserVisitor
{
  public String visit(SimpleNode node, String data);
  public String visit(SSLStart node, String data);
  public String visit(SSLAddStatement node, String data);
  public String visit(SSLDoStatement node, String data);
  public String visit(SSLUpdateStatement node, String data);
  public String visit(SSLQuantifier node, String data);
  public String visit(SSLNumber node, String data);
  public String visit(SSLAll node, String data);
  public String visit(SSLClass node, String data);
  public String visit(SSLAssignments node, String data);
  public String visit(SSLAssignment node, String data);
  public String visit(SSLProperty node, String data);
  public String visit(SSLValue node, String data);
}
/* JavaCC - OriginalChecksum=c1f40e3298b91153e68783cdd4ee1ecd (do not edit this line) */
