package ssl;
/* Generated By:JJTree: Do not edit this line. SSLAssignment.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLAssignment extends SimpleNode {
  public SSLAssignment(int id) {
    super(id);
  }

  public SSLAssignment(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f7905dc44fb28db9118c747ad9304caa (do not edit this line) */
