package ssl;
/* Generated By:JJTree: Do not edit this line. SSLAddStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLAddStatement extends SimpleNode {
  public SSLAddStatement(int id) {
    super(id);
  }

  public SSLAddStatement(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=79f9a732e9e93929b4c8af3c2394e2d8 (do not edit this line) */
