package ssl;
/* Generated By:JJTree: Do not edit this line. SSLAssignments.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLAssignments extends SimpleNode {
  public SSLAssignments(int id) {
    super(id);
  }

  public SSLAssignments(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=9a3451bee26fa48a7c5dc3e28b4c8f2f (do not edit this line) */
