package ssl;
/* Generated By:JJTree: Do not edit this line. SSLDoStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLDoStatement extends SimpleNode {
  public SSLDoStatement(int id) {
    super(id);
  }

  public SSLDoStatement(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=e1eb6baecc2da5f0bed0be6788ad1932 (do not edit this line) */
