package ssl;
/* Generated By:JJTree: Do not edit this line. SSLLinkStatement.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLLinkStatement extends SimpleNode {
  public SSLLinkStatement(int id) {
    super(id);
  }

  public SSLLinkStatement(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f8d747204ecbf287762f9cc8071ddeb4 (do not edit this line) */
