package ssl;
/* Generated By:JJTree: Do not edit this line. SSLOclExp.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLOclExp extends SimpleNode {
  public SSLOclExp(int id) {
    super(id);
  }

  public SSLOclExp(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=b3f7a877a561226389d3974313bf8dd6 (do not edit this line) */
