package ssl;
/* Generated By:JJTree: Do not edit this line. SSLProperty.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLProperty extends SimpleNode {
  public SSLProperty(int id) {
    super(id);
  }

  public SSLProperty(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=8c94dba2a63d0e500cdcd520f598864b (do not edit this line) */
