package ssl;
/* Generated By:JJTree: Do not edit this line. SSLQuantifier.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLQuantifier extends SimpleNode {
  public SSLQuantifier(int id) {
    super(id);
  }

  public SSLQuantifier(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=743891fee9329f6ed6e850b4d4764183 (do not edit this line) */
