package ssl;
/* Generated By:JJTree: Do not edit this line. SSLUpdateCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLUpdateCondition extends SimpleNode {
  public SSLUpdateCondition(int id) {
    super(id);
  }

  public SSLUpdateCondition(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f28fedbde65723e2aa7c74c7fd085823 (do not edit this line) */
