package ssl;
/* Generated By:JJTree: Do not edit this line. SSLWhereCondition.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=SSL,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
public
class SSLWhereCondition extends SimpleNode {
  public SSLWhereCondition(int id) {
    super(id);
  }

  public SSLWhereCondition(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public String jjtAccept(ExpressionParserVisitor visitor, String data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=ce9b64f54d7977876f6b5dbb79c65798 (do not edit this line) */
